const SAVE_KEY="perfect-crossing-save-v1";const MAX_LEVEL=5000;
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function hashSeed(n){let x=(n|0)^0x9e3779b9;x=Math.imul(x^(x>>>16),0x85ebca6b);x=Math.imul(x^(x>>>13),0xc2b2ae35);return (x^(x>>>16))>>>0}
function rng(seed){let s=seed>>>0;return()=>{s=(s+0x6d2b79f5)>>>0;let t=s;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
function difficulty(level){const t=Math.min(1,(level-1)/4999);return{lanes:clamp(2+Math.floor(t*7),2,9),speed:70+t*170,density:.24+t*.5,gap:Math.max(.18,.58-t*.36),vehicleScale:1+t*.45}}
function makeLevel(level){const d=difficulty(level),random=rng(hashSeed(level));const lanes=d.lanes;const cars=[];for(let lane=0;lane<lanes;lane++){const count=1+Math.floor(d.density*3+(random()>.55?1:0));for(let i=0;i<count;i++){cars.push({lane,x:random()*100,width:(7+random()*8)*d.vehicleScale,speed:d.speed*(.72+random()*.65)*(random()>.5?1:-1),phase:random()})}}return{level,lanes,cars}}
function validateLevel(data){if(!data||data.lanes<2||data.cars.length<1)return false;const byLane=Array.from({length:data.lanes},()=>[]);data.cars.forEach(c=>byLane[c.lane].push(c));return byLane.every(cars=>cars.length>0&&cars.length<6)}
const defaultSave={level:1,cash:0,gems:0,completed:0,noHit:0,streak:0,tasks:{five:0,fifteen:0,clean:0,fifty:0,hundred:0}};
function loadSave(){try{return{...defaultSave,...JSON.parse(localStorage.getItem(SAVE_KEY)||"{}")}}catch{return{...defaultSave}}}
let save=loadSave(),state={level:save.level,player:0,running:true,hit:false,started:false,levelData:null,last:performance.now(),cars:[]};
const board=document.querySelector("#board"),cashEl=document.querySelector("#cash"),gemsEl=document.querySelector("#gems"),levelEl=document.querySelector("#level"),message=document.querySelector("#message"),moveButton=document.querySelector("#moveButton"),modal=document.querySelector("#modal"),modalTitle=document.querySelector("#modalTitle"),modalText=document.querySelector("#modalText"),modalButton=document.querySelector("#modalButton");
function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify(save))}
function rewardCash(level){return Math.round(10+Math.sqrt(level)*6.8)}
function renderHud(){cashEl.textContent="£"+save.cash.toLocaleString("en-GB");gemsEl.textContent=save.gems.toLocaleString("en-GB");levelEl.textContent=state.level.toLocaleString("en-GB")}
function showModal(title,text,next){modalTitle.textContent=title;modalText.textContent=text;modalButton.textContent=next?"NEXT LEVEL":"TRY AGAIN";modal.classList.remove("hidden")}
function hideModal(){modal.classList.add("hidden")}
function build(){let tries=0;do{state.levelData=makeLevel(state.level);tries++}while(!validateLevel(state.levelData)&&tries<20);state.player=0;state.running=true;state.hit=false;state.started=false;state.last=performance.now();state.cars=state.levelData.cars.map(c=>({...c,x:c.x}));render()}
function render(){board.replaceChildren();const h=board.clientHeight||500,laneH=h/(state.levelData.lanes+2);const grassTop=laneH,grassBottom=laneH;const top=document.createElement("div");top.className="grass";top.style.top="0";top.style.height=grassTop+"px";board.append(top);const bottom=document.createElement("div");bottom.className="grass";bottom.style.bottom="0";bottom.style.height=grassBottom+"px";board.append(bottom);for(let i=0;i<state.levelData.lanes;i++){const lane=document.createElement("div");lane.className="lane";lane.style.top=(grassTop+i*laneH)+"px";lane.style.height=laneH+"px";board.append(lane)}state.cars.forEach((car,i)=>{const el=document.createElement("div");el.className="car";el.dataset.i=i;el.style.width=car.width+"%";el.style.left=car.x+"%";el.style.top=(grassTop+car.lane*laneH+laneH*.29)+"px";board.append(el)});const p=document.createElement("div");p.className="player";p.textContent="🧍";p.setAttribute("aria-label","Player");p.style.left="calc(50% - 19px)";p.style.bottom=(grassBottom+state.player*laneH+laneH*.31)+"px";board.append(p)}
function move(){if(!state.running)return;if(state.player>=state.levelData.lanes){complete();return}state.started=true;state.player++;if(state.player>state.levelData.lanes){complete();return}checkCollision();render();if(state.player===state.levelData.lanes){message.textContent="One more move!";}else message.textContent="Watch the traffic";if(state.player>=state.levelData.lanes)complete()}
function checkCollision(){const row=state.player-1;if(row<0)return;const d=difficulty(state.level),gap=d.gap*100;const danger=state.cars.filter(c=>c.lane===row).some(c=>{let x=c.x;if(c.speed<0)x=(100-x-c.width+100)%100;return Math.abs((x+c.width/2)-50)<(gap*0.5+c.width/2)});if(danger)fail()}
function fail(){state.running=false;state.hit=true;save.streak=0;persist();message.textContent="You got hit!";showModal("CRASH!","The traffic caught you. Your level stays unlocked so you can try again.",false)}
function complete(){if(!state.running)return;state.running=false;const reward=rewardCash(state.level),clean=!state.hit;save.cash+=reward;save.completed++;save.streak++;save.tasks.five=Math.max(save.tasks.five,state.level);if(clean){save.noHit++;save.gems+=15}if(save.completed%5===0)save.gems+=10;if(save.completed%15===0)save.gems+=25;if(save.completed%50===0)save.gems+=50;if(save.completed%100===0)save.gems+=100;if(state.level<MAX_LEVEL)save.level=state.level+1;persist();renderHud();message.textContent="Level complete!";const bonus=clean?" +15 gems for a clean crossing.":"";showModal("LEVEL COMPLETE",`Cash +£${reward}.${bonus}`,state.level<MAX_LEVEL)}
function frame(now){const dt=Math.min(.05,(now-state.last)/1000);state.last=now;if(state.running&&state.started){const d=difficulty(state.level);state.cars.forEach(c=>{c.x+=(c.speed/100)*dt;if(c.x>105)c.x=-c.width;if(c.x<-c.width)c.x=105});if(state.player>0)checkCollision();render()}requestAnimationFrame(frame)}
moveButton.addEventListener("click",move);board.addEventListener("pointerdown",e=>{if(e.pointerType==="touch"||e.pointerType==="pen")move()});modalButton.addEventListener("click",()=>{hideModal();if(state.hit){build()}else{state.level=Math.min(MAX_LEVEL,state.level+1);save.level=state.level;persist();renderHud();build()}});document.querySelectorAll(".nav-button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".nav-button").forEach(x=>x.classList.remove("active"));b.classList.add("active");if(b.dataset.screen==="tasks"){message.textContent="Tasks: 5 levels = +10 gems · 15 levels = +25 gems · clean crossing = +15 gems";}else if(b.dataset.screen==="shop"){message.textContent="Shop is coming after the core game loop is proven."; }else message.textContent="Tap the road to move";}));
renderHud();build();requestAnimationFrame(frame);