(()=>{"use strict";
const C=window.PopPartyCore,$=id=>document.getElementById(id),STORE="pop-party-save-v1",RUN_STORE="pop-party-run-v1";
function characterMarkup(tile){if(typeof tile!=="number")return tile==="rocket"?"<span class='power-art rocket-art'>➜</span>":tile==="bomb"?"<span class='power-art bomb-art'>✹</span>":"<span class='power-art rainbow-art'>✦</span>";return "<span class='tile-dot' aria-hidden='true'></span>";}
function fxBurst(x,y,type="pop"){const root=$("fx-layer");if(!root)return;const burst=document.createElement("div");burst.className="fx-burst "+type;burst.style.left=x+"px";burst.style.top=y+"px";for(let n=0;n<8;n++){const p=document.createElement("i");p.style.setProperty("--a",n/8*360+"deg");p.style.setProperty("--d",24+Math.random()*42+"px");burst.appendChild(p);}root.appendChild(burst);setTimeout(()=>burst.remove(),700);}
function boardBurst(indices,type="pop"){const boardEl=$("board");indices.slice(0,18).forEach((i,n)=>{const el=boardEl.querySelector('[data-index="'+i+'"]');if(!el)return;const r=el.getBoundingClientRect();setTimeout(()=>fxBurst(r.left+r.width/2,r.top+r.height/2,type),n*16);});}
function matchBurst(count,power){const el=document.createElement("div");el.className="match-burst";const strong=document.createElement("strong"),label=document.createElement("span");strong.textContent=count+" TILES";label.textContent=power?power.toUpperCase()+" BLAST":count>=8?"MEGA POP!":count>=6?"BIG POP!":count>=4?"GREAT POP!":"NICE POP!";el.append(strong,label);$("fx-layer").appendChild(el);setTimeout(()=>el.remove(),850);}
function juiceBoard(){const el=document.querySelector(".board-wrap");if(!el)return;el.classList.remove("board-hit");void el.offsetWidth;el.classList.add("board-hit");setTimeout(()=>el.classList.remove("board-hit"),320);}
let progress=loadProgress(),level=1,board=[],moves=25,score=0,collected={},busy=false,seed=Date.now()>>>0,config,toastTimer,advanceTimer=null,modalAction=null,modalSecondaryAction=null,audioContext=null,pendingPower=null,dailyMode=false,dailyChallenge=null;
function loadProgress(){try{return C.sanitiseProgress(JSON.parse(localStorage.getItem(STORE)));}catch{return C.newProgress();}}
function save(){try{localStorage.setItem(STORE,JSON.stringify(progress));}catch{}}
function saveRun(){try{if(!config||board.length!==C.ROWS*C.COLS){localStorage.removeItem(RUN_STORE);return;}localStorage.setItem(RUN_STORE,JSON.stringify({level,board,moves,score,collected,seed,mode:dailyMode?"daily":"level",dailyDate:dailyMode&&dailyChallenge?dailyChallenge.date:""}));}catch{}}
function clearRun(){try{localStorage.removeItem(RUN_STORE);}catch{}}
function loadRun(){try{return C.sanitiseRun(JSON.parse(localStorage.getItem(RUN_STORE)));}catch{return null;}}
function randomSeed(){seed=(seed+0x9e3779b9)>>>0;return seed;}
function playSound(type){if(!progress.sound)return;const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)return;try{audioContext=audioContext||new AudioCtor();if(audioContext.state==="suspended")audioContext.resume();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime,start=type==="win"?660:type==="power"?360:500,end=type==="win"?990:type==="power"?160:760;oscillator.type="sine";oscillator.frequency.setValueAtTime(start,now);oscillator.frequency.exponentialRampToValueAtTime(end,now+.12);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.07,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+.14);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(now);oscillator.stop(now+.15);}catch{}}
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),1700);}
function startLevel(n){dailyMode=false;dailyChallenge=null;clearTimeout(advanceTimer);advanceTimer=null;n=Math.max(1,Math.min(C.MAX_LEVEL,Number(n)||1));if(n>progress.unlocked){toast("Finish the previous level first!");return;}level=n;progress.lastLevel=level;save();showGameScreen();config=C.levelConfig(level);moves=config.moves;score=0;collected={};busy=false;board=C.createBoard(level,randomSeed());$("level-number").textContent=level;$("goal-title").textContent="Clear "+config.targets.reduce((s,t)=>s+t.count,0)+" tiles";$("goal-subtitle").textContent=level<5?"Choose a group. No automatic chain clears.":"Plan each pop and save moves. Chains are manual.";$("board-message").textContent="Tap 2+ matching blocks";$("combo-label").textContent="READY";render();updateHud();saveRun();closeModal();}
function render(){const el=$("board");el.classList.toggle("placement-mode",!!pendingPower);el.innerHTML="";board.forEach((tile,i)=>{const b=document.createElement("button");b.type="button";b.className="tile "+(tile===null?"empty":typeof tile==="string"?"power-"+tile:"c"+tile);b.setAttribute("role","gridcell");b.setAttribute("aria-label",tile===null?"Empty":typeof tile==="string"?tile+" power-up":"Colour tile");b.dataset.index=i;if(tile===null)b.disabled=true;else{const f=document.createElement("span");f.className="face expression-normal";f.innerHTML=characterMarkup(tile);b.appendChild(f);b.addEventListener("click",()=>tapTile(i));}el.appendChild(b);});}
function updateHud(){$("moves-left").textContent=moves;$("coin-count").textContent=progress.coins;$("home-coins").textContent=progress.coins||0;$("score-count").textContent=score;$("progress-fill").style.width=Math.min(100,score/Math.max(1,config.targetScore)*100)+"%";$("goals").innerHTML="";config.targets.forEach(t=>{const got=Math.min(t.count,collected[t.colour]||0),chip=document.createElement("div");chip.className="goal-chip"+(got>=t.count?" done":"");const face=document.createElement("span");face.className="goal-mini goal-swatch c"+t.colour;face.setAttribute("aria-hidden","true");const label=document.createElement("span");label.className="goal-name";label.textContent=["Pink","Yellow","Blue","Purple","Green","Orange"][t.colour]||"Colour";const count=document.createElement("span");count.className="goal-count";count.textContent=got+"/"+t.count;chip.setAttribute("aria-label",label.textContent+" blocks: "+got+" of "+t.count);chip.append(face,label,count);$("goals").appendChild(chip);});["rocket","bomb"].forEach(k=>$(k+"-count").textContent=progress.boosters[k]||0);}
const ACHIEVEMENTS=[{id:"first-pop",title:"First Pop",detail:"Pop your first group",reward:10,check:s=>s.pops>=1},{id:"ten-pops",title:"Pop Party",detail:"Pop 10 groups",reward:20,check:s=>s.pops>=10},{id:"first-win",title:"Star Player",detail:"Complete a level",reward:25,check:s=>s.levelsCompleted>=1},{id:"five-levels",title:"On a Roll",detail:"Complete 5 levels",reward:50,check:s=>s.levelsCompleted>=5}];
function localDateKey(){const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");}
function refreshDaily(){const today=localDateKey();if(!progress.daily)progress.daily=C.newProgress().daily;if(progress.daily.date!==today){progress.daily.date=today;progress.daily.completed=progress.daily.lastCompleted===today;}progress.daily.streak=Math.max(0,progress.daily.streak||0);progress.daily.bestScore=Math.max(0,progress.daily.bestScore||0);}
function awardAchievements(){for(const a of ACHIEVEMENTS){if(!progress.achievements[a.id]&&a.check(progress.stats)){progress.achievements[a.id]=true;progress.coins+=a.reward;toast(a.title+" unlocked! +"+a.reward+" coins");}}}
function recordPop(tileCount){progress.stats.pops++;progress.stats.tilesCleared+=tileCount;awardAchievements();save();renderHome();}
function renderHome(){if(!$("home-level-number"))return;const unlocked=Math.max(1,progress.unlocked);$("home-level-number").textContent=unlocked;$("home-coins").textContent=progress.coins||0;$("coin-count").textContent=progress.coins||0;refreshDaily();const daily=progress.daily,challenge=C.dailyChallenge(localDateKey());$("daily-title").textContent="Daily puzzle #"+String(challenge.seed%10000).padStart(4,"0");$("daily-progress").textContent=daily.completed?"Completed today · "+daily.streak+" day streak · Best "+daily.bestScore+" pts":"Fixed puzzle · Clear both colour goals · "+challenge.config.moves+" moves";$("daily-fill").style.width=daily.completed?"100%":"0%";$("daily-play").textContent=daily.completed?"REPLAY TODAY":"PLAY TODAY";$("daily-play").setAttribute("aria-label",daily.completed?"Replay today's daily challenge":"Play today's daily challenge");$("achievement-count").textContent=Object.keys(progress.achievements).length+"/"+ACHIEVEMENTS.length;const list=$("achievement-list");list.innerHTML="";for(const a of ACHIEVEMENTS){const item=document.createElement("div");item.className="achievement-item"+(progress.achievements[a.id]?" earned":"");item.innerHTML="<span class='achievement-medal'>"+(progress.achievements[a.id]?"🏆":"☆")+"</span><span class='achievement-text'><strong>"+a.title+"</strong><small>"+a.detail+"</small></span><span class='achievement-reward'>"+(progress.achievements[a.id]?"✓":"+"+a.reward+" 🪙")+"</span>";list.appendChild(item);}}
function targetComplete(){return config.targets.every(t=>(collected[t.colour]||0)>=t.count);}
function startDailyChallenge(){refreshDaily();clearTimeout(advanceTimer);advanceTimer=null;dailyMode=true;dailyChallenge=C.dailyChallenge(localDateKey());level=dailyChallenge.level;config=dailyChallenge.config;seed=dailyChallenge.seed;moves=config.moves;score=0;collected={};busy=false;pendingPower=null;board=C.createBoard(level,randomSeed());showGameScreen();$("level-number").textContent="★";$("goal-title").textContent="Daily puzzle #"+String(dailyChallenge.seed%10000).padStart(4,"0");$("goal-subtitle").textContent="Same puzzle for everyone today · No automatic chains";$("board-message").textContent="Daily challenge · Good luck!";$("combo-label").textContent="DAILY";render();updateHud();saveRun();closeModal();}
$("daily-play").addEventListener("click",startDailyChallenge);
function setExpression(i,state){const el=$("board")?.querySelector('[data-index="'+i+'"]');if(el){el.classList.remove("expression-selected","expression-popping","expression-winning");el.classList.add("expression-"+state);}}
function tapTile(i){if(busy)return;if(pendingPower){pendingPower=null;}document.querySelectorAll(".tile.expression-selected").forEach(el=>el.classList.remove("expression-selected"));setExpression(i,"selected");if(typeof board[i]==="string"){clearGroup([i],board[i]);return;}const group=C.groupAt(board,i);if(group.length<2){setExpression(i,"normal");toast("Match 2 or more blocks.");return;}const power=group.length>=9?"rainbow":group.length>=5?"bomb":group.length>=4?"rocket":null;if(power){createPower(group,power);return;}clearGroup(group,null);}
function createPower(group,power){if(busy)return;busy=true;group.forEach(i=>setExpression(i,"popping"));const at=group[Math.floor(group.length/2)],cleared=group.length-1;group.forEach(i=>{if(i!==at){const tile=$("board").querySelector('[data-index="'+i+'"]');if(tile)tile.classList.add("popping");const v=board[i];if(typeof v==="number")collected[v]=(collected[v]||0)+1;board[i]=null;}});score+=C.scoreForGroup(cleared);moves--;recordPop(cleared);matchBurst(cleared,power);juiceBoard();playSound("power");board[at]=power;boardBurst(group,"power");$("board-message").textContent=power==="bomb"?"BOMB READY!":"ROCKET READY!";updateHud();board=C.refill(C.applyGravity(board),level,randomSeed());saveRun();setTimeout(()=>{busy=false;render();updateHud();if(targetComplete())winLevel();else if(moves<=0)loseLevel();else if(!C.hasMove(board)){board=C.createBoard(level,randomSeed());render();saveRun();toast("Fresh board!");}},320);}
function clearGroup(indices,power){if(busy)return;busy=true;const all=new Set(indices);if(power==="rocket"){const row=Math.floor(indices[0]/C.COLS);for(let x=0;x<C.COLS;x++)all.add(row*C.COLS+x);}else if(power==="bomb"){const centre=indices[0],cx=centre%C.COLS,cy=Math.floor(centre/C.COLS);for(let y=Math.max(0,cy-1);y<=Math.min(C.ROWS-1,cy+1);y++)for(let x=Math.max(0,cx-1);x<=Math.min(C.COLS-1,cx+1);x++)all.add(y*C.COLS+x);}else if(power==="rainbow"){const counts=Array(C.COLOURS).fill(0);board.forEach(v=>{if(typeof v==="number")counts[v]++;});const colour=counts.indexOf(Math.max(...counts));board.forEach((v,i)=>{if(v===colour)all.add(i);});}
const valid=[...all].filter(i=>board[i]!==null&&board[i]!==undefined);if(!valid.length){busy=false;return;}const n=valid.length;boardBurst(valid,power?"power":"pop");valid.forEach(i=>{const tile=$("board").querySelector('[data-index="'+i+'"]');if(tile)tile.classList.add("popping");const value=board[i];if(typeof value==="number")collected[value]=(collected[value]||0)+1;board[i]=null;});score+=C.scoreForGroup(n);moves--;recordPop(n);matchBurst(n,power);juiceBoard();playSound(power?"power":"pop");if(progress.vibration&&navigator.vibrate)navigator.vibrate(power?24:10);$("combo-label").textContent=n>=8?"MEGA POP!":n>=6?"BIG POP!":n>=4?"GREAT POP!":"POP!";$("board-message").textContent=power?power.toUpperCase()+" BLAST!":n>=6?"Huge group! +"+C.scoreForGroup(n)+" points":"Nice pop! +"+C.scoreForGroup(n)+" points";updateHud();board=C.refill(C.applyGravity(board),level,randomSeed());saveRun();setTimeout(()=>{render();busy=false;updateHud();if(targetComplete())winLevel();else if(moves<=0)loseLevel();else if(!C.hasMove(board)){board=C.createBoard(level,randomSeed());render();saveRun();toast("Fresh board!");}},260);}
function celebrate(){document.querySelectorAll(".tile:not(.empty)").forEach(el=>el.classList.add("expression-winning"));const root=$("fx-layer");if(!root)return;for(let i=0;i<30;i++){const p=document.createElement("i");p.className="confetti";p.style.left=15+Math.random()*70+"%";p.style.setProperty("--x",Math.random()*180-90+"px");p.style.setProperty("--r",Math.random()*720-360+"deg");root.appendChild(p);setTimeout(()=>p.remove(),1300);}}
function winLevel(){if(busy)return;busy=true;clearRun();const key=String(level),old=progress.levels[key],firstCompletion=!old,previousBest=old?old.score:0;let earned=firstCompletion?10+Math.floor(score/100):0;if(firstCompletion){progress.stats.levelsCompleted=(progress.stats.levelsCompleted||0)+1;if(progress.stats.levelsCompleted%5===0)earned+=25;}progress.levels[key]={score:Math.max(previousBest,score)};progress.coins+=earned;progress.stats.wins++;progress.unlocked=Math.min(C.MAX_LEVEL,Math.max(progress.unlocked,level+1));awardAchievements();save();updateHud();renderHome();playSound("win");celebrate();busy=false;const rewardText=earned?earned+" coins":"Best score updated";const copy=firstCompletion?(progress.stats.levelsCompleted%5===0?"Milestone reached! You cleared level "+level+" and earned a bonus.":"You cleared level "+level+" and unlocked the next stop."):"Level "+level+" replay complete. First-clear coins are only awarded once.";showModal("🏆","LEVEL COMPLETE!",copy,"<div class='modal-stats'><div class='modal-stat'><span>"+rewardText+"</span>"+(earned?"level reward":"replay reward")+"</div><div class='modal-stat'><span>★ "+(progress.levels[key].score>previousBest?"New score":"Best score")+"</span>best run</div></div>","View level map",()=>showHomeScreen(),"Play next level");}
function loseLevel(){clearRun();const cleared=Object.values(collected).reduce((sum,value)=>sum+value,0);showModal("💪","OUT OF MOVES","You scored "+score+" points and cleared "+cleared+" tiles. Try a different plan and make every move count.","<div class=\'modal-stats\'><div class=\'modal-stat\'><span>"+score+"</span>score</div><div class=\'modal-stat\'><span>"+moves+"</span>moves left</div><div class=\'modal-stat\'><span>"+cleared+"</span>tiles cleared</div></div>","Try again",()=>startLevel(level),"Back home");}
function showModal(emoji,title,copy,extra,primary,action,secondary){$("modal-close").classList.remove("hidden");const modal=$("modal-backdrop").querySelector(".modal");modal.classList.remove("modal-win","modal-loss");if(title==="LEVEL COMPLETE!")modal.classList.add("modal-win");if(title==="OUT OF MOVES")modal.classList.add("modal-loss");$("modal-emoji").textContent=emoji;$("modal-title").textContent=title;$("modal-copy").textContent=copy;$("modal-extra").innerHTML=extra||"";$("modal-primary").textContent=primary||"Keep popping!";$("modal-secondary").classList.toggle("hidden",!secondary);$("modal-secondary").textContent=secondary||"Try again";$("modal-share").classList.toggle("hidden",title!=="LEVEL COMPLETE!"&&title!=="OUT OF MOVES");modalAction=action;modalSecondaryAction=secondary?(title==="LEVEL COMPLETE!"?()=>startLevel(Math.min(C.MAX_LEVEL,level+1)):title==="OUT OF MOVES"?()=>showHomeScreen():()=>startLevel(level)):null;$("modal-backdrop").classList.remove("hidden");}
function closeModal(){$("modal-backdrop").classList.add("hidden");}
async function shareResult(){const url=location.href;const text="I scored "+score+" points on Pop Party, level "+level+"! Can you beat me?";if(navigator.share){try{await navigator.share({title:"Pop Party challenge",text,url});return;}catch(error){if(error&&error.name==="AbortError")return;}}try{if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(text+" "+url);toast("Challenge copied - send it to a friend!");}else{toast("Sharing unavailable in this browser.");}}catch{toast("Could not copy the challenge. Try your browser Share option.");}}
$("modal-primary").addEventListener("click",()=>{const a=modalAction;closeModal();if(a)a();});$("modal-secondary").addEventListener("click",()=>{const a=modalSecondaryAction;closeModal();if(a)a();else startLevel(level);});$("modal-close").addEventListener("click",closeModal);$("modal-share").addEventListener("click",shareResult);
function settings(){showModal("","SETTINGS","Choose your game preferences.",'<label class="setting-row">Sound effects <input id="setting-sound" type="checkbox" '+(progress.sound?"checked":"")+'></label><label class="setting-row">Vibration <input id="setting-vibration" type="checkbox" '+(progress.vibration?"checked":"")+'></label><label class="setting-row">Reset progress <button id="reset-progress" class="secondary-button" style="width:auto;margin:0;padding:7px 10px">Reset</button></label>',"Save",()=>{progress.sound=$("setting-sound").checked;progress.vibration=$("setting-vibration").checked;save();toast("Saved");});$("reset-progress").addEventListener("click",()=>showModal("","START FRESH?","This resets your local coins, levels and boosters.","","Reset progress",()=>{progress=C.newProgress();clearRun();save();showHomeScreen();}));}
$("settings-button").addEventListener("click",()=>{if(busy){toast("Finish the pop first!");return;}settings();});
document.querySelectorAll("[data-power]").forEach(b=>b.addEventListener("click",()=>usePower(b.dataset.power)));
function placeBooster(type){const choices=board.map((tile,i)=>typeof tile==="number"?i:-1).filter(i=>i>=0);if(!choices.length){toast("No colour blocks available.");return;}const i=choices[Math.floor(Math.random()*choices.length)];board[i]=type;progress.boosters[type]=Math.max(0,(progress.boosters[type]||0)-1);pendingPower=null;save();saveRun();render();updateHud();toast(type.toUpperCase()+" added to a block! Tap it when you want to use it.");}function usePower(type){if(busy)return;if(type==="shuffle"){if((progress.boosters.shuffle||0)<=0&&progress.coins<25){toast("You need 25 coins.");return;}if((progress.boosters.shuffle||0)>0)progress.boosters.shuffle--;else progress.coins-=25;board=C.createBoard(level,randomSeed());save();saveRun();render();updateHud();toast("Fresh possibilities!");return;}if((progress.boosters[type]||0)<=0){if(progress.coins>=25)showModal("","BOOSTER","Trade 25 coins for one "+type+". It will automatically turn a colour block into a booster; tap that block later to activate it.","","Get booster · 25 coins",()=>{progress.coins-=25;progress.boosters[type]=(progress.boosters[type]||0)+1;save();placeBooster(type);});else toast("Win levels to earn coins.");return;}placeBooster(type);}
function showHomeScreen(){clearTimeout(advanceTimer);advanceTimer=null;busy=false;$("home-screen")?.classList.remove("hidden");$("game-screen")?.classList.add("hidden");renderHome();}
function showGameScreen(){$("home-screen")?.classList.add("hidden");$("game-screen")?.classList.remove("hidden");}
$("play-level-button").addEventListener("click",()=>startLevel(progress.unlocked));
$("brand")?.addEventListener("click",e=>{e.preventDefault();if(busy){toast("Finish the pop first!");return;}closeModal();showHomeScreen();});
function init(){refreshDaily();if(!$("fx-layer")){const fx=document.createElement("div");fx.id="fx-layer";fx.setAttribute("aria-hidden","true");document.body.appendChild(fx);}progress.unlocked=Math.max(1,progress.unlocked);save();const run=loadRun();if(run&&run.level<=progress.unlocked){level=run.level;config=C.levelConfig(level);board=run.board;moves=run.moves;score=run.score;collected=run.collected;seed=run.seed;busy=false;pendingPower=null;showGameScreen();$("level-number").textContent=level;$("goal-title").textContent="Clear "+config.targets.reduce((s,t)=>s+t.count,0)+" tiles";$("goal-subtitle").textContent=level<5?"Choose a group. No automatic chain clears.":"Plan each pop and save moves. Chains are manual.";$("board-message").textContent="Run restored";$("combo-label").textContent="RESUMED";render();updateHud();saveRun();if(targetComplete())winLevel();else if(moves<=0)loseLevel();}else{if(run)clearRun();showHomeScreen();}renderHome();if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("./sw.js").catch(()=>{});}
init();
})();