(()=>{"use strict";
const C=window.PopPartyCore,$=id=>document.getElementById(id),STORE="pop-party-save-v1";
function characterMarkup(tile){if(typeof tile!=="number")return tile==="rocket"?"<span class='power-art rocket-art'>➜</span>":tile==="bomb"?"<span class='power-art bomb-art'>✹</span>":"<span class='power-art rainbow-art'>✦</span>";return "<span class='tile-dot' aria-hidden='true'></span>";}
function fxBurst(x,y,type="pop"){const root=$("fx-layer");if(!root)return;const burst=document.createElement("div");burst.className="fx-burst "+type;burst.style.left=x+"px";burst.style.top=y+"px";for(let n=0;n<8;n++){const p=document.createElement("i");p.style.setProperty("--a",n/8*360+"deg");p.style.setProperty("--d",24+Math.random()*42+"px");burst.appendChild(p);}root.appendChild(burst);setTimeout(()=>burst.remove(),700);}
function boardBurst(indices,type="pop"){const boardEl=$("board");indices.slice(0,18).forEach((i,n)=>{const el=boardEl.querySelector('[data-index="'+i+'"]');if(!el)return;const r=el.getBoundingClientRect();setTimeout(()=>fxBurst(r.left+r.width/2,r.top+r.height/2,type),n*16);});}
function comboBurst(level){const el=document.createElement("div");el.className="combo-burst";el.innerHTML="<strong>"+level+"x</strong><span>COMBO!</span>";$("fx-layer").appendChild(el);setTimeout(()=>el.remove(),900);}
let progress=loadProgress(),level=1,board=[],moves=25,score=0,collected={},busy=false,combo=0,seed=Date.now()>>>0,config,toastTimer,modalAction=null;
function loadProgress(){try{return C.sanitiseProgress(JSON.parse(localStorage.getItem(STORE)));}catch{return C.newProgress();}}
function save(){try{localStorage.setItem(STORE,JSON.stringify(progress));}catch{}}
function randomSeed(){seed=(seed+0x9e3779b9)>>>0;return seed;}
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),1700);}
function startLevel(n){n=Math.max(1,Math.min(C.MAX_LEVEL,Number(n)||1));if(n!==progress.unlocked){toast("Finish the previous level first!");return;}level=n;progress.lastLevel=level;save();showGameScreen();config=C.levelConfig(level);moves=config.moves;score=0;combo=0;collected={};busy=false;board=C.createBoard(level,randomSeed());$("level-number").textContent=level;$("goal-title").textContent="Clear "+config.targets.reduce((s,t)=>s+t.count,0)+" tiles";$("goal-subtitle").textContent=level<5?"Build a combo to clear faster.":"Plan your pops and save moves.";$("board-message").textContent="Tap 2+ matching blocks";$("combo-label").textContent="READY";render();updateHud();closeModal();}
function render(){const el=$("board");el.innerHTML="";board.forEach((tile,i)=>{const b=document.createElement("button");b.type="button";b.className="tile "+(tile===null?"empty":typeof tile==="string"?"power-"+tile:"c"+tile);b.setAttribute("role","gridcell");b.setAttribute("aria-label",tile===null?"Empty":typeof tile==="string"?tile+" power-up":"Colour tile");b.dataset.index=i;if(tile===null)b.disabled=true;else{const f=document.createElement("span");f.className="face expression-normal";f.innerHTML=characterMarkup(tile);b.appendChild(f);b.addEventListener("click",()=>tapTile(i));}el.appendChild(b);});}
function updateHud(){$("moves-left").textContent=moves;$("coin-count").textContent=progress.coins;$("home-coins").textContent=progress.coins||0;$("score-count").textContent=score;$("progress-fill").style.width=Math.min(100,score/Math.max(1,config.targetScore)*100)+"%";$("goals").innerHTML="";config.targets.forEach(t=>{const got=Math.min(t.count,collected[t.colour]||0),chip=document.createElement("div");chip.className="goal-chip"+(got>=t.count?" done":"");const face=document.createElement("span");face.className="goal-mini";face.innerHTML=characterMarkup(t.colour);const count=document.createElement("span");count.textContent=got+"/"+t.count;chip.append(face,count);$("goals").appendChild(chip);});["rocket","bomb"].forEach(k=>$(k+"-count").textContent=progress.boosters[k]||0);}
function targetComplete(){return config.targets.every(t=>(collected[t.colour]||0)>=t.count);}
function setExpression(i,state){const el=$("board")?.querySelector('[data-index="'+i+'"]');if(el){el.classList.remove("expression-selected","expression-popping","expression-winning");el.classList.add("expression-"+state);}}
function tapTile(i){if(busy)return;document.querySelectorAll(".tile.expression-selected").forEach(el=>el.classList.remove("expression-selected"));setExpression(i,"selected");if(typeof board[i]==="string"){clearGroup([i],board[i]);return;}const group=C.groupAt(board,i);if(group.length<2){setExpression(i,"normal");toast("Match 2 or more blocks.");return;}const power=group.length>=9?"rainbow":group.length>=5?"bomb":group.length>=4?"rocket":null;if(power){createPower(group,power);return;}clearGroup(group,null);}
function createPower(group,power){if(busy)return;busy=true;group.forEach(i=>setExpression(i,"popping"));const at=group[Math.floor(group.length/2)];group.forEach(i=>{if(i!==at){const tile=$("board").querySelector('[data-index="'+i+'"]');if(tile)tile.classList.add("popping");const v=board[i];if(typeof v==="number")collected[v]=(collected[v]||0)+1;board[i]=null;}});score+=C.scoreForGroup(group.length);moves--;combo++;board[at]=power;boardBurst(group,"power");$("board-message").textContent=power==="bomb"?"BOMB READY!":"ROCKET READY!";updateHud();setTimeout(()=>{board=C.applyGravity(board);board=C.refill(board,level,randomSeed());busy=false;render();updateHud();if(targetComplete())winLevel();else if(moves<=0)loseLevel();},320);}
function clearGroup(indices,power){if(busy)return;busy=true;const all=new Set(indices);if(power==="rocket"){const row=Math.floor(indices[0]/C.COLS);for(let x=0;x<C.COLS;x++)all.add(row*C.COLS+x);}else if(power==="bomb"){const centre=indices[0],cx=centre%C.COLS,cy=Math.floor(centre/C.COLS);for(let y=Math.max(0,cy-1);y<=Math.min(C.ROWS-1,cy+1);y++)for(let x=Math.max(0,cx-1);x<=Math.min(C.COLS-1,cx+1);x++)all.add(y*C.COLS+x);}else if(power==="rainbow"){const counts=Array(C.COLOURS).fill(0);board.forEach(v=>{if(typeof v==="number")counts[v]++;});const colour=counts.indexOf(Math.max(...counts));board.forEach((v,i)=>{if(v===colour)all.add(i);});}
const valid=[...all].filter(i=>board[i]!==null&&board[i]!==undefined);if(!valid.length){busy=false;return;}const n=valid.length;boardBurst(valid,power?"power":"pop");valid.forEach(i=>{const tile=$("board").querySelector('[data-index="'+i+'"]');if(tile)tile.classList.add("popping");const value=board[i];if(typeof value==="number")collected[value]=(collected[value]||0)+1;board[i]=null;});const multiplier=combo>0?combo+1:1;score+=C.scoreForGroup(n)*multiplier;moves--;combo++;if(progress.sound&&navigator.vibrate&&progress.vibration)navigator.vibrate(power?24:10);$("combo-label").textContent=combo>1?combo+"x COMBO":"POP!";$("board-message").textContent=power?power.toUpperCase()+" BLAST!":combo>1?"Chain reaction!":"Nice pop!";if(combo>1)comboBurst(combo);updateHud();setTimeout(()=>{board=C.applyGravity(board);board=C.refill(board,level,randomSeed());render();const cascade=findCascade();if(cascade.length){toast("Cascade!");setTimeout(()=>clearGroup(cascade,null),140);return;}busy=false;updateHud();if(targetComplete())winLevel();else if(moves<=0)loseLevel();else if(!C.hasMove(board)){board=C.createBoard(level,randomSeed());render();toast("Fresh board!");}},260);}
function findCascade(){for(let i=0;i<board.length;i++){const g=C.groupAt(board,i);if(g.length>=5)return g;}return[];}
function celebrate(){document.querySelectorAll(".tile:not(.empty)").forEach(el=>el.classList.add("expression-winning"));const root=$("fx-layer");if(!root)return;for(let i=0;i<30;i++){const p=document.createElement("i");p.className="confetti";p.style.left=15+Math.random()*70+"%";p.style.setProperty("--x",Math.random()*180-90+"px");p.style.setProperty("--r",Math.random()*720-360+"deg");root.appendChild(p);setTimeout(()=>p.remove(),1300);}}
function winLevel(){if(busy)return;busy=true;const key=String(level),old=progress.levels[key]||{score:0},earned=10+Math.floor(score/100);progress.levels[key]={score:Math.max(old.score,score)};progress.coins+=earned;progress.unlocked=Math.min(C.MAX_LEVEL,level+1);save();updateHud();celebrate();if(level>=C.MAX_LEVEL){busy=false;showModal("","ALL LEVELS COMPLETE","You cleared every Pop Party level.","<div class='modal-stats'><div class='modal-stat'><span>"+earned+" coins</span>earned</div></div>","Back home",()=>showHomeScreen());return;}toast("Level "+(level+1)+" unlocked!");setTimeout(()=>{busy=false;startLevel(level+1);},900);}
function loseLevel(){showModal("","SO CLOSE!","Try a different plan and build a bigger combo.","","Try again",()=>startLevel(level));}
function showModal(emoji,title,copy,extra,primary,action,secondary){$("modal-emoji").textContent=emoji;$("modal-title").textContent=title;$("modal-copy").textContent=copy;$("modal-extra").innerHTML=extra||"";$("modal-primary").textContent=primary||"Keep popping!";$("modal-secondary").classList.toggle("hidden",!secondary);$("modal-secondary").textContent=secondary||"Try again";modalAction=action;$("modal-backdrop").classList.remove("hidden");}
function closeModal(){$("modal-backdrop").classList.add("hidden");}
$("modal-primary").addEventListener("click",()=>{const a=modalAction;closeModal();if(a)a();});$("modal-secondary").addEventListener("click",()=>{closeModal();startLevel(level);});$("modal-close").addEventListener("click",closeModal);
function settings(){showModal("","SETTINGS","Choose your game preferences.",'<label class="setting-row">Sound effects <input id="setting-sound" type="checkbox" '+(progress.sound?"checked":"")+'></label><label class="setting-row">Vibration <input id="setting-vibration" type="checkbox" '+(progress.vibration?"checked":"")+'></label><label class="setting-row">Reset progress <button id="reset-progress" class="secondary-button" style="width:auto;margin:0;padding:7px 10px">Reset</button></label>',"Save",()=>{progress.sound=$("setting-sound").checked;progress.vibration=$("setting-vibration").checked;save();toast("Saved");});$("reset-progress").addEventListener("click",()=>showModal("","START FRESH?","This resets your local coins, levels and boosters.","","Reset progress",()=>{progress=C.newProgress();save();showHomeScreen();}));}
$("settings-button").addEventListener("click",settings);
document.querySelectorAll("[data-power]").forEach(b=>b.addEventListener("click",()=>usePower(b.dataset.power)));
function usePower(type){if(busy)return;if(type==="shuffle"){if((progress.boosters.shuffle||0)<=0&&progress.coins<25){toast("You need 25 coins.");return;}if((progress.boosters.shuffle||0)>0)progress.boosters.shuffle--;else progress.coins-=25;board=C.createBoard(level,randomSeed());save();render();updateHud();toast("Fresh possibilities!");return;}if((progress.boosters[type]||0)<=0){if(progress.coins>=25)showModal("","BOOSTER","Trade 25 coins for one "+type+".","","Get booster · 25 coins",()=>{progress.coins-=25;progress.boosters[type]=(progress.boosters[type]||0)+1;save();updateHud();usePower(type);});else toast("Win levels to earn coins.");return;}progress.boosters[type]--;save();const i=board.findIndex(v=>v!==null);if(i<0){busy=false;return;}clearGroup([i],type);updateHud();}
function showHomeScreen(){$("home-screen")?.classList.remove("hidden");$("game-screen")?.classList.add("hidden");$("home-level-number").textContent=progress.unlocked;$("home-coins").textContent=progress.coins||0;}
function showGameScreen(){$("home-screen")?.classList.add("hidden");$("game-screen")?.classList.remove("hidden");}
$("play-level-button").addEventListener("click",()=>startLevel(progress.unlocked));
$("brand")?.addEventListener("click",e=>{e.preventDefault();closeModal();showHomeScreen();});
function init(){if(!$("fx-layer")){const fx=document.createElement("div");fx.id="fx-layer";fx.setAttribute("aria-hidden","true");document.body.appendChild(fx);}progress.unlocked=Math.max(1,progress.unlocked);save();showHomeScreen();if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("./sw.js").catch(()=>{});}
init();
})();