(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.PopPartyCore=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
"use strict";
const COLS=8,ROWS=9,COLOURS=6,MAX_LEVEL=5000;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function rng(seed){let s=(seed>>>0)||1;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function createBoard(level,seed){const rand=rng((seed||level*2654435761)>>>0),board=Array(ROWS*COLS).fill(null);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){let options=Array.from({length:COLOURS},(_,i)=>i);if(x>1&&board[y*COLS+x-1]===board[y*COLS+x-2])options=options.filter(c=>c!==board[y*COLS+x-1]);if(y>1&&board[(y-1)*COLS+x]===board[(y-2)*COLS+x])options=options.filter(c=>c!==board[(y-2)*COLS+x]);board[y*COLS+x]=options[Math.floor(rand()*options.length)];}if(!hasMove(board)){board[0]=board[1];if(board[1]===board[2])board[2]=(board[1]+1)%COLOURS;if(board[8]===board[16])board[8]=(board[0]+1)%COLOURS;}const n=Math.max(1,Math.floor(Number(level)||1)),obstacleCount=n<4?0:Math.min(8,1+Math.floor(n/8));for(let placed=0;placed<obstacleCount;){const candidates=[];for(let i=0;i<board.length;i++){if(typeof board[i]!=="number"||groupAt(board,i).length!==1)continue;const near=neighbours(i);if(near.some(j=>typeof board[j]==="string"))continue;candidates.push(i);}if(!candidates.length)break;const at=candidates[Math.floor(rand()*candidates.length)];board[at]=n>=8&&rand()<.38?"ice":"crate";placed++;}return board;}function neighbours(index){const x=index%COLS,y=Math.floor(index/COLS),out=[];if(x>0)out.push(index-1);if(x<COLS-1)out.push(index+1);if(y>0)out.push(index-COLS);if(y<ROWS-1)out.push(index+COLS);return out;}
function groupAt(board,index){if(!board||!Number.isInteger(index)||index<0||index>=board.length||board[index]===null||board[index]===undefined||typeof board[index]!=="number"||board[index]<0)return[];const colour=board[index],seen=new Set([index]),stack=[index];while(stack.length){for(const n of neighbours(stack.pop()))if(!seen.has(n)&&board[n]===colour){seen.add(n);stack.push(n);}}return[...seen].sort((a,b)=>a-b);}
function hasMove(board){for(let i=0;i<board.length;i++)if(groupAt(board,i).length>=2)return true;return false;}
function hasPlayableMove(board){return hasMove(board)||!!(Array.isArray(board)&&board.some(v=>v==="rocket"||v==="bomb"||v==="rainbow"));}
function applyGravity(board){const next=Array(ROWS*COLS).fill(null);for(let x=0;x<COLS;x++){let y=ROWS-1;for(let from=ROWS-1;from>=0;from--){const v=board[from*COLS+x];if(v!==null&&v!==undefined){next[y*COLS+x]=v;y--;}}}return next;}
function refill(board,level,seed){const rand=rng((seed+level*104729)>>>0),next=board.slice();for(let i=0;i<next.length;i++)if(next[i]===null||next[i]===undefined)next[i]=Math.floor(rand()*COLOURS);return next;}
function levelConfig(level){const n=clamp(Math.floor(Number(level)||1),1,MAX_LEVEL),moves=clamp(25-Math.floor((n-1)/5),18,25),a=Math.min(24,8+Math.floor(n*.35)),second=Math.max(5,Math.floor(a*.4));return{level:n,moves,targets:[{colour:(n-1)%COLOURS,count:a},{colour:(n+2)%COLOURS,count:second}],targetScore:a*10};}
function scoreForGroup(size){return size*10+Math.max(0,size-2)*Math.max(0,size-2)*5;}
function dailyChallenge(date){const text=String(date||"");let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}const seed=(h>>>0)||1,level=1+(seed%20);return{date:text,seed,level,config:levelConfig(level)};}
function dailyStreak(lastCompleted,streak,today){if(lastCompleted===today)return Math.max(1,Number(streak)||1);const d=new Date(today+"T12:00:00");d.setDate(d.getDate()-1);const yesterday=d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");return lastCompleted===yesterday?Math.max(0,Number(streak)||0)+1:1;}function completeDaily(raw,today,score){const source=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw:{};const daily={date:typeof source.date==="string"?source.date:"",completed:source.completed===true,streak:clamp(Number(source.streak)||0,0,999999),lastCompleted:typeof source.lastCompleted==="string"?source.lastCompleted:"",bestScore:clamp(Number(source.bestScore)||0,0,999999999)};const already=daily.lastCompleted===today;daily.date=today;if(!already){daily.streak=dailyStreak(daily.lastCompleted,daily.streak,today);daily.lastCompleted=today;}daily.completed=true;daily.bestScore=Math.max(daily.bestScore,clamp(Number(score)||0,0,999999999));const reward=already?0:25+Math.min(25,Math.max(0,daily.streak-1)*5);return{daily,reward,already};}
function newProgress(){return{unlocked:1,coins:50,levels:{},boosters:{rocket:2,bomb:1,shuffle:1},sound:true,vibration:true,daily:{date:"",completed:false,streak:0,lastCompleted:"",bestScore:0},achievements:{},stats:{pops:0,wins:0,levelsCompleted:0,tilesCleared:0}};}
function sanitiseRun(raw){if(!raw||typeof raw!=="object"||Array.isArray(raw)||!Number.isInteger(raw.level)||raw.level<1||raw.level>MAX_LEVEL||!Array.isArray(raw.board)||raw.board.length!==ROWS*COLS)return null;const board=raw.board.map(v=>v===null?null:(Number.isInteger(v)&&v>=0&&v<COLOURS?v:(v==="rocket"||v==="bomb"||v==="rainbow"||v==="crate"||v==="ice"||v==="cracked-ice"?v:undefined)));if(board.some(v=>v===undefined))return null;const moves=Number(raw.moves),score=Number(raw.score);if(!Number.isInteger(moves)||moves<0||moves>25||!Number.isFinite(score)||score<0)return null;const source=raw.collected&&typeof raw.collected==="object"&&!Array.isArray(raw.collected)?raw.collected:{};const collected={};for(let c=0;c<COLOURS;c++)collected[c]=clamp(Number(source[c])||0,0,999999);return{level:raw.level,board,moves,score:clamp(score,0,999999999),collected,seed:Number(raw.seed)>>>0,...(raw.mode==="daily"?{mode:"daily",dailyDate:typeof raw.dailyDate==="string"?raw.dailyDate:""}:{})};}
function sanitiseProgress(raw){const base=newProgress();if(!raw||typeof raw!=="object"||Array.isArray(raw))return base;const sourceBoosters=raw.boosters&&typeof raw.boosters==="object"&&!Array.isArray(raw.boosters)?raw.boosters:{};const levels=raw.levels&&typeof raw.levels==="object"&&!Array.isArray(raw.levels)?Object.fromEntries(Object.entries(raw.levels).filter(([key,value])=>/^\d+$/.test(key)&&value&&typeof value==="object"&&!Array.isArray(value)).map(([key,value])=>[key,{score:clamp(Number(value.score)||0,0,999999999)}])):{};const d=raw.daily&&typeof raw.daily==="object"&&!Array.isArray(raw.daily)?raw.daily:{},a=raw.achievements&&typeof raw.achievements==="object"&&!Array.isArray(raw.achievements)?raw.achievements:{},st=raw.stats&&typeof raw.stats==="object"&&!Array.isArray(raw.stats)?raw.stats:{};return{unlocked:clamp(Number(raw.unlocked)||1,1,MAX_LEVEL),coins:clamp(Number(raw.coins)||0,0,999999999),levels,boosters:{rocket:sourceBoosters.rocket===undefined?base.boosters.rocket:clamp(Number(sourceBoosters.rocket)||0,0,999),bomb:sourceBoosters.bomb===undefined?base.boosters.bomb:clamp(Number(sourceBoosters.bomb)||0,0,999),shuffle:sourceBoosters.shuffle===undefined?base.boosters.shuffle:clamp(Number(sourceBoosters.shuffle)||0,0,999)},sound:raw.sound!==false,vibration:raw.vibration!==false,daily:{date:typeof d.date==="string"?d.date:"",completed:d.completed===true,streak:clamp(Number(d.streak)||0,0,999999),lastCompleted:typeof d.lastCompleted==="string"?d.lastCompleted:"",bestScore:clamp(Number(d.bestScore)||0,0,999999999)},achievements:Object.fromEntries(["first-pop","ten-pops","first-win","five-levels"].filter(k=>a[k]===true).map(k=>[k,true])),stats:{pops:clamp(Number(st.pops)||0,0,999999999),wins:clamp(Number(st.wins)||0,0,999999999),levelsCompleted:Math.max(clamp(Number(st.levelsCompleted)||0,0,999999999),Object.keys(levels).length),tilesCleared:clamp(Number(st.tilesCleared)||0,0,999999999)}};}
return{COLS,ROWS,COLOURS,MAX_LEVEL,rng,createBoard,neighbours,groupAt,hasMove,hasPlayableMove,applyGravity,refill,levelConfig,scoreForGroup,dailyChallenge,dailyStreak,completeDaily,newProgress,sanitiseProgress,sanitiseRun};
});