const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");

const coreSource = fs.readFileSync("game-core.js", "utf8");
const context = { console, globalThis: {} };
vm.runInNewContext(coreSource, context, { filename: "game-core.js" });
const core = context.globalThis.PERFECT_CROSSING_CORE;

assert.ok(core);
assert.equal(core.MAX_LEVEL, 5000);
assert.equal(core.SIMULATION_DT, 1 / 60);

function snapshot(level) {
  return JSON.stringify(core.makeLevel(level));
}

// Determinism: repeated generation must produce byte-identical levels.
for (const level of [1, 2, 10, 100, 1000, 2500, 5000]) {
  assert.equal(snapshot(level), snapshot(level), "level " + level + " must be deterministic");
  assert.equal(snapshot(level), snapshot(level), "level " + level + " changed between generations");
}

// Every level must be generated by the authoritative solver and remain deterministic.
for (let level = 1; level <= core.MAX_LEVEL; level++) {
  const generated = core.makeLevel(level);
  assert.equal(generated.level, level);
  assert.equal(generated.lanes, core.difficulty(level).lanes);
  assert.ok(core.authoritativeSolve(level, generated.cars), "level " + level + " is not completable");
  assert.equal(
    JSON.stringify(generated),
    JSON.stringify(core.makeLevel(level)),
    "level " + level + " is not deterministic"
  );
}

// Traffic movement and collision use the same geometry as the solver.
const testCars = [{ lane: 1, x: 49, width: 10, speed: 0, kind: "car", height: 36 }];
assert.equal(core.collisionAt(testCars, 2, 1, 0), true);
assert.equal(core.collisionAt(testCars, 2, 2, 0), false);
assert.equal(core.collisionAt([{ ...testCars[0], x: 0 }], 2, 1, 0), false);

const moving = [{ lane: 1, x: 0, width: 10, speed: 60, kind: "car", height: 36 }];
const afterOneSecond = core.advanceTraffic(moving, 1);
assert.equal(afterOneSecond[0].x, 60);
assert.equal(core.advanceTraffic(moving, 1)[0].x, 60);

// Progression and rewards.
let save = core.defaultSave();
save = core.completeLevel(save, 1, true);
assert.equal(save.completed, 1);
assert.equal(save.level, 2);
assert.equal(save.cash, core.rewardCash(1));
assert.equal(save.gems, 15);
assert.equal(save.streak, 1);

for (let i = 2; i <= 5; i++) {
  save = core.completeLevel(save, i, true);
}
assert.equal(save.completed, 5);
assert.equal(save.level, 6);
assert.ok(save.gems >= 25, "5-level reward should be applied");

let maxSave = core.defaultSave();
for (let level = 1; level <= core.MAX_LEVEL; level++) {
  maxSave = core.completeLevel(maxSave, level, false);
}
assert.equal(maxSave.level, core.MAX_LEVEL);
assert.equal(maxSave.completed, core.MAX_LEVEL);

assert.match(fs.readFileSync("game.js", "utf8"), /advanceTraffic/);
assert.match(fs.readFileSync("game.js", "utf8"), /updateRenderPositions/);
assert.match(fs.readFileSync("game.js", "utf8"), /checkCollision/);

console.log("Perfect Crossing: 5000-level generation, authoritative solvability, determinism, collision, movement and progression checks passed.");
